<?php
/**
 * N Framework
 *
 * WARNING: This file is part of the core N Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @since      0.0.1
 * @package    N
 * @subpackage N/includes/admin
 */

if (!defined('ABSPATH')):
	exit; // Exit if accessed directly.
endif;

/**
 * Ghi đè lời cảm ơn
 *
 * @since    0.0.1
 */
function _n_footer_text(){
	echo '<span id="footer-thankyou">Cảm ơn bạn đã khởi tạo với  <a href="https://nhut.me/" target="_blank">N Framework</a> powered by <a href="https://vi.wordpress.org/" target="_blank">WordPress</a></span>';
}

add_action('admin_footer_text', '_n_footer_text', 11);
