<?php
/**
 * N Framework
 *
 * WARNING: This file is part of the core N Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @since      0.0.1
 * @package    N
 * @subpackage N/includes/functions
 */

if (!defined('ABSPATH')):
	exit; // Exit if accessed directly.
endif;

/**
 * @since 0.0.1
 */
function _n_markup($args = []){
	$defaults = [
		'context' => '',
		'open'    => '',
		'close'   => '',
		'attrs'   => [],
		'content' => '',
		'echo'    => true,
	];

	$args = wp_parse_args($args, $defaults);

	if ($args['context']):
		$open    = $args['open'] ? sprintf($args['open'], _n_attr($args['context'], $args['attrs'], $args)) : '';
		$open    = apply_filters("_n_markup_{$args['context']}_open", $open, $args);
		$close   = apply_filters("_n_markup_{$args['context']}_close", $args['close'], $args);
		$content = apply_filters("_n_markup_{$args['context']}_content", $args['content'], $args);
	else:
		$open    = $args['open'];
		$close   = $args['close'];
		$content = $args['content'];
	endif;

	if ($open || $args['content']):
		$open = apply_filters('_n_markup_open', $open, $args);
	endif;

	if ($close || $args['content']):
		$close = apply_filters('_n_markup_close', $close, $args);
	endif;

	if ($args['echo']) :
		echo $open . $content . $close;

		return null;
	endif;

	return $open . $content . $close;
}

/**
 * @since 0.0.1
 */
function _n_parse_attr($context, $attributes = [], $args = []){
	$defaults = [
		'class' => sanitize_html_class($context),
	];

	$attributes = wp_parse_args($attributes, $defaults);

	return apply_filters("_n_{$context}", $attributes, $context, $args);
}

/**
 * @since 0.0.1
 */
function _n_attr($context, $attributes = [], $args = []){
	$attributes = _n_parse_attr($context, $attributes, $args);
	$output     = '';

	foreach ($attributes as $key => $value):
		if (!$value):
			continue;
		endif;

		if (true === $value):
			$output .= esc_html($key) . ' ';
		else:
			$output .= sprintf('%s="%s" ', esc_html($key), esc_attr($value));
		endif;
	endforeach;

	$output = apply_filters("_n_attr_{$context}_output", $output, $attributes, $context, $args);

	return trim($output);
}
