<?php
/**
 * N Framework
 *
 * WARNING: This file is part of the core N Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @since      0.0.1
 * @package    N
 * @subpackage N/includes/functions
 */

if (!defined('ABSPATH')):
	exit; // Exit if accessed directly.
endif;

/**
 * Get the framework.
 *
 * @since 0.0.1
 */
function _n_framework(){
	NFramework::get()->get_framework();
}

/**
 * Get breadcrumbs
 *
 * @since      0.0.1
 */
function _n_get_breadcrumbs($args = []){
	return NBreadcrumbs::get() ? NBreadcrumbs::get()->get_breadcrumb($args) : '';
}

/**
 * Output breadcrumbs.
 *
 * @since      0.0.1
 */
function _n_breadcrumbs($args = []){
	echo _n_get_breadcrumbs($args);
}

/**
 * Get pagination
 *
 * @since      0.0.1
 */
function _n_get_pagination($args = []){
	return NPagination::get() ? NPagination::get()->get_pagination($args) : '';
}

/**
 * Output pagination.
 *
 * @since      0.0.1
 */
function _n_pagination($args = []){
	echo _n_get_pagination($args);
}
