<?php
/**
 * N Framework
 *
 * WARNING: This file is part of the core N Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @since      0.0.1
 * @package    N
 * @subpackage N/includes/functions
 */

if (!defined('ABSPATH')):
	exit; // Exit if accessed directly.
endif;

/**
 * Disable woocommerce default stylesheet.
 */
add_filter('woocommerce_enqueue_styles', '__return_empty_array');

/**
 * Disable single search result redirect
 */
add_filter('woocommerce_redirect_single_search_result', '__return_false');

/**
 * Disable automatic wizard redirect
 */
add_filter('woocommerce_prevent_automatic_wizard_redirect', 'auto_redirect', 20, 1);

/**
 * Override WooCommerce template files
 *
 * @since 0.0.1
 */
function _n_override_woocommerce_templates($template){
	global $post;
	$post_type = "";

	if (isset($post->post_type)):
		$post_type = $post->post_type;
	endif;

	if ($post_type == "product" || is_product() || is_product_category() || is_product_tag() || is_shop()):
		$new_template = locate_template(['index.php'], false);

		if (!empty($new_template)):
			return $new_template;
		endif;
	endif;

	return $template;
}

add_filter('template_include', '_n_override_woocommerce_templates', 11);

/**
 * Remove woocommerce features
 */
function _n_woocommerce_admin_features($features){
	return array_values(
		array_filter($features, function ($feature){
			return !in_array($feature, ['marketing', 'analytics', 'analytics-dashboard', 'analytics-dashboard/customizable', 'wc-admin', 'wc-pay-welcome-page']);
		})
	);
}

add_filter('woocommerce_admin_features', '_n_woocommerce_admin_features');

/**
 * Remove woocommerce admin menu
 */
function _n_woocommerce_remove_admin_menus(){
	$remove = ['wc-admin', 'wc-status', 'wc-addons'];

	foreach ($remove as $submenu_slug):
		remove_submenu_page('woocommerce', $submenu_slug);
	endforeach;
}

add_action('admin_menu', '_n_woocommerce_remove_admin_menus', 99, 0);

/**
 * Woocommerce change admin label
 */
function _n_woocommerce_change_admin_label(){
	global $menu;

	$menu['55.5'][0] = __('Cửa hàng', 'viecommerce');
}

add_action('admin_menu', '_n_woocommerce_change_admin_label');
