<?php
/**
 * N Framework
 *
 * WARNING: This file is part of the core N Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @since      0.0.1
 * @package    N
 * @subpackage N/lib/functions
 */

if (!defined('ABSPATH')):
	exit; // Exit if accessed directly.
endif;

/**
 * Tìm kiếm nâng cao
 *
 * @since 0.0.1
 */
function _n_package_advanced_search($query){
	if ($query->is_search):
		$s                      = isset($_GET['s']) ? esc_attr($_GET['s']) : '';
		$post_type              = isset($_GET['post_type']) ? esc_attr($_GET['post_type']) : '';
		$package_data           = isset($_GET['package_data']) ? esc_attr($_GET['package_data']) : '';
		$package_super_data     = isset($_GET['package_super_data']) ? esc_attr($_GET['package_super_data']) : '';
		$package_special_offers = isset($_GET['package_special_offers']) ? esc_attr($_GET['package_special_offers']) : '';
		$cheap                  = isset($_GET['cheap']) ? esc_attr($_GET['cheap']) : '';
		$package_call           = isset($_GET['package_call']) ? esc_attr($_GET['package_call']) : '';
		$package_sms            = isset($_GET['package_sms']) ? esc_attr($_GET['package_sms']) : '';
		$package_day            = isset($_GET['package_day']) ? esc_attr($_GET['package_day']) : '';
		$package_month          = isset($_GET['package_month']) ? esc_attr($_GET['package_month']) : '';
		$package_year           = isset($_GET['package_year']) ? esc_attr($_GET['package_year']) : '';
		$price                  = isset($_GET['price']) ? esc_attr($_GET['price']) : 0;
		$mno                    = isset($_GET['mno']) ? esc_attr($_GET['mno']) : '';

		if ($post_type == 'package'):
			if ($mno != ''):
				$meta_query[] = [
					'key'     => '_mno',
					'value'   => $mno,
					'compare' => '=',
				];
			endif;

			if ($package_data != '' && $package_data == 'yes'):
				$meta_query[] = [
					'relation' => 'OR',
					[
						'key'     => '_package_is_data',
						'value'   => 'yes',
						'compare' => '=',
					],
					[
						'key'     => '_package_is_data',
						'value'   => "1",
						'compare' => '=',
					],
				];
			endif;

			if ($package_super_data != '' && $package_super_data == 'yes'):
				$meta_query[] = [
					'relation' => 'OR',
					[
						'key'     => '_package_super_data',
						'value'   => 'yes',
						'compare' => '=',
					],
					[
						'key'     => '_package_super_data',
						'value'   => "1",
						'compare' => '=',
					],
				];
			endif;

			if ($package_special_offers != '' && $package_special_offers == 'yes'):
				$meta_query[] = [
					'relation' => 'OR',
					[
						'key'     => '_package_special_offers',
						'value'   => 'yes',
						'compare' => '=',
					],
					[
						'key'     => '_package_special_offers',
						'value'   => "1",
						'compare' => '=',
					],
				];
			endif;

			if ($package_call != '' && $package_call == 'yes'):
				$meta_query[] = [
					'relation' => 'OR',
					[
						'key'     => '_package_call',
						'value'   => 'yes',
						'compare' => '=',
					],
					[
						'key'     => '_package_call',
						'value'   => "1",
						'compare' => '=',
					],
				];
			endif;

			if ($cheap != '' && $cheap == 'yes'):
				$meta_query[] = [
					'relation' => 'OR',
					[
						'key'     => '_package_price',
						'value'   => 'yes',
						'compare' => '=',
					],
					[
						'key'     => '_package_price',
						'value'   => "1",
						'compare' => '=',
					],
				];
			endif;

			if ($package_sms != '' && $package_sms == 'yes'):
				$meta_query[] = [
					'relation' => 'OR',
					[
						'key'     => '_package_sms',
						'value'   => 'yes',
						'compare' => '=',
					],
					[
						'key'     => '_package_sms',
						'value'   => "1",
						'compare' => '=',
					],
				];
			endif;

			if ($package_day != '' && $package_day == 'yes'):
				$meta_query[] = [
					'relation' => 'OR',
					[
						'key'     => '_package_day',
						'value'   => 'yes',
						'compare' => '=',
					],
					[
						'key'     => '_package_day',
						'value'   => "1",
						'compare' => '=',
					],
				];
			endif;

			if ($package_month != '' && $package_month == 'yes'):
				$meta_query[] = [
					'relation' => 'OR',
					[
						'key'     => '_package_month',
						'value'   => 'yes',
						'compare' => '=',
					],
					[
						'key'     => '_package_month',
						'value'   => "1",
						'compare' => '=',
					],
				];
			endif;

			if ($package_year != '' && $package_year == 'yes'):
				$meta_query[] = [
					'relation' => 'OR',
					[
						'key'     => '_package_year',
						'value'   => 'yes',
						'compare' => '=',
					],
					[
						'key'     => '_package_year',
						'value'   => "1",
						'compare' => '=',
					],
				];
			endif;

			if ($price == 1):
				$meta_query[] = [
					'key'     => '_package_price',
					'value'   => [0, 50000],
					'type'    => 'numeric',
					'compare' => 'BETWEEN',
				];
			elseif ($price == 2):
				$meta_query[] = [
					'key'     => '_package_price',
					'value'   => [50000, 100000],
					'type'    => 'numeric',
					'compare' => 'BETWEEN',
				];
			elseif ($price == 3):
				$meta_query[] = [
					'key'     => '_package_price',
					'value'   => [100000, 200000],
					'type'    => 'numeric',
					'compare' => 'BETWEEN',
				];
			elseif ($price == 4):
				$meta_query[] = [
					'key'     => '_package_price',
					'value'   => [200000, 1000000],
					'type'    => 'numeric',
					'compare' => 'BETWEEN',
				];
			elseif ($price == 5):
				$meta_query[] = [
					'key'     => '_package_price',
					'value'   => 1000000,
					'type'    => 'numeric',
					'compare' => '>',
				];
			endif;

			$meta_query['relation'] = 'AND';
			$query->set('meta_query', $meta_query);
		endif;
	endif;
}

add_filter('pre_get_posts', '_n_package_advanced_search');
