<?php
/**
 * N Framework
 *
 * WARNING: This file is part of the core N Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @since      0.0.1
 * @package    N
 * @subpackage N/lib/functions
 */

if (!defined('ABSPATH')):
	exit; // Exit if accessed directly.
endif;

/**
 * Đăng nhập API
 *
 * @since 0.0.1
 */
function _n_api_login(){
	$general_settings = get_field('_theme_general_settings', 'option');
	$username         = $general_settings['_api_username'];
	$password         = $general_settings['_api_password'];
	$url              = 'https://congtacvien.mobifone.vn/aff-api/api/authenticate';

	$headers = [
		'Content-Type' => 'application/json',
	];

	$body = [
		"username" => $username,
		"password" => $password
	];

	$response = wp_remote_post($url, [
		'timeout'   => 60,
		'headers'   => $headers,
		'body'      => json_encode($body),
		'sslverify' => false
	]);

	if (is_wp_error($response)):
		return $response->get_error_message();
	else:
		return json_decode(wp_remote_retrieve_body($response));
	endif;
}

/**
 * Đăng nhập API
 *
 * @since 0.0.1
 */
function _n_api_login_2(){
	$general_settings = get_field('_theme_general_settings', 'option');
	$username         = $general_settings['_api_username'];
	$password         = $general_settings['_api_password'];
	$url              = 'https://congtacvien.mobifone.vn/admin/j_spring_security_check';

	$headers = [
		'Content-Type' => 'application/x-www-form-urlencoded; charset=UTF-8',
	];

	$body = "username={$username}&password={$password}&code_captcha=";

	$cookies = [];

	$cookies[] = new WP_Http_Cookie([
		'name'  => 'WEB_AFF_SESSIONID007',
		'value' => _n_generate_cookie(),
	]);

	$response = wp_remote_post($url, [
		'timeout'   => 60,
		'headers'   => $headers,
		'body'      => $body,
		'sslverify' => false,
		'cookies'   => $cookies
	]);

	if (is_wp_error($response)):
		return $response->get_error_message();
	else:
		return wp_remote_retrieve_cookies($response);
	endif;
}

/**
 * Gửi otp cho khách hàng
 *
 * @since 0.0.1
 */
function _n_api_get_otp($args = []){
	$authenticate = _n_api_login();
	$token        = $authenticate->data->token;
	$url          = 'https://congtacvien.mobifone.vn/aff-api/api/transPackage/getOtp';

	$defaults = [
		"msisdn"   => '',
		"pckCode"  => '',
		"userName" => $authenticate->data->userDetails->username,
		'source'   => 'API Tài Phát',
		'cusId'    => '',
	];

	$headers = [
		'Content-Type'  => 'application/json',
		'Authorization' => 'Bearer ' . $token,
	];

	$body = wp_parse_args($args, $defaults);

	$response = wp_remote_post($url, [
		'timeout'   => 60,
		'headers'   => $headers,
		'body'      => json_encode($body),
		'sslverify' => false
	]);

	if (is_wp_error($response)):
		return $response->get_error_message();
	else:
		return json_decode(wp_remote_retrieve_body($response));
	endif;
}

function _n_api_package_recommend($phone, $page){
	$authenticate = _n_api_login();
	$url          = 'https://congtacvien.mobifone.vn/admin/goi-cuoc/tim-kiem-goi-goi-y';
	$token        = $authenticate->data->token;

	if (!$authenticate):
		return false;
	endif;

	$headers = [
		'Content-Type'  => 'application/json',
		'Authorization' => 'Bearer ' . $token,
	];

	$params = [
		"msisdn"     => $phone,
		"pageNumber" => $page,
	];

	$url = $url . '?' . http_build_query($params);

	$response = wp_remote_get($url, [
		'headers'   => $headers,
		'sslverify' => false,
		'cookies'   => _n_api_login_2(),
	]);

	if (is_wp_error($response)):
		return $response->get_error_message();
	else:
		return json_decode(wp_remote_retrieve_body($response));
	endif;
}

function _n_api_package_list(){
	$phone = isset($_POST['phone-number']) ? strval($_POST['phone-number']) : '';
	$page  = isset($_POST['page']) ? strval($_POST['page']) : '';

	_n_create_client_data([
		'phone'  => $phone,
		'action' => 'Tìm gói gói cước đề xuất theo thuê bao, đang xem trang ' . $page,
	]);

	$response = _n_api_package_recommend($phone, $page);
	wp_send_json_success($response);
	wp_die();
}

add_action('wp_ajax_package_search', '_n_api_package_list');
add_action('wp_ajax_nopriv_package_search', '_n_api_package_list');

/**
 * Đăng ký gói cước bằng API
 *
 * @since 0.0.1
 */
function _n_register_package_otp(){
	$phone   = isset($_POST['phone-number']) ? strval($_POST['phone-number']) : '';
	$package = isset($_POST['package-name']) ? strval($_POST['package-name']) : '';
	date_default_timezone_set('Asia/Ho_Chi_Minh');

	$data = [
		"msisdn"  => $phone,
		"pckCode" => $package,
	];

	$response = _n_api_get_otp($data);

	if (!empty($response->data->respContent)):
		$status = $response->data->respContent;
	else:
		$status = $response->message;
	endif;

	_n_create_client_data([
		'phone'  => $phone,
		'action' => 'Đăng ký gói cước  ' . $package . ' qua OTP',
	]);

	if ($response->success):
		$success   = 'Thành công';
		$recommend = [];
	else:
		$success   = 'Thất bại';
		$recommend = _n_api_package_recommend($phone, '1');
	endif;

	$data = [
		"phone"     => $phone,
		"package"   => $package,
		"response"  => $response,
		"recommend" => $recommend,
	];

	$args = [
		'post_type'  => 'package',
		'meta_query' => [
			[
				'key'     => '_package_name',
				'value'   => $package,
				'compare' => '=',
			]
		]
	];

	$posts = get_posts($args);
	$price = 0;

	if (!empty($posts) && !is_wp_error($posts)):
		$post_id = $posts[0]->ID;
		$price   = get_post_meta($post_id, '_package_price', true);
	endif;

	_n_send_telegram_message([
		'phone'      => $phone,
		'date'       => date("Y-m-d H:i"),
		'status'     => $status,
		'channel'    => 'OTP',
		'is_success' => $success,
		'code'       => $package,
		'price'      => $price,
	]);

	wp_send_json_success($data);

	wp_die();
}

add_action('wp_ajax_register_package_otp', '_n_register_package_otp');
add_action('wp_ajax_nopriv_register_package_otp', '_n_register_package_otp');

/**
 * Xác nhậ OTP
 *
 * @since 0.0.1
 */
function _n_confirm_package_otp(){
	$phone    = isset($_POST['phone-number']) ? strval($_POST['phone-number']) : '';
	$package  = isset($_POST['package-name']) ? strval($_POST['package-name']) : '';
	$username = isset($_POST['username']) ? strval($_POST['username']) : '';
	$otp      = isset($_POST['otp']) ? strval($_POST['otp']) : '';
	date_default_timezone_set('Asia/Ho_Chi_Minh');

	$authenticate = _n_api_login();
	$token        = $authenticate->data->token;
	$url          = 'https://congtacvien.mobifone.vn/aff-api/api/transPackage/otpConfirm';

	$headers = [
		'Content-Type'  => 'application/json',
		'Authorization' => 'Bearer ' . $token,
	];

	$body = [
		'msisdn'   => $phone,
		'pckCode'  => $package,
		'userName' => $username,
		'otp'      => $otp,
	];

	_n_create_client_data([
		'phone'  => $phone,
		'action' => 'Xác thực OTP, mã OTP là ' . $otp,
	]);

	$response = wp_remote_post($url, [
		'timeout'   => 60,
		'headers'   => $headers,
		'body'      => json_encode($body),
		'sslverify' => false
	]);

	if (is_wp_error($response)):
		wp_send_json_error($response->get_error_message());
	else:
		$data = json_decode(wp_remote_retrieve_body($response));

		if (!empty($data->data->respContent)):
			$status = $data->data->respContent;
		else:
			$status = $data->message;
		endif;

		if ($data->success):
			$success   = 'Thành công';
			$recommend = [];
		else:
			$success   = 'Thất bại';
			$recommend = _n_api_package_recommend($phone, '1');
		endif;

		$args = [
			'post_type'  => 'package',
			'meta_query' => [
				[
					'key'     => '_package_name',
					'value'   => $package,
					'compare' => '=',
				]
			]
		];

		$posts = get_posts($args);
		$price = 0;

		if (!empty($posts) && !is_wp_error($posts)):
			$post_id = $posts[0]->ID;
			$price   = get_post_meta($post_id, '_package_price', true);
		endif;

		_n_send_telegram_message([
			'phone'      => $phone,
			'date'       => date("Y-m-d H:i"),
			'status'     => $status,
			'channel'    => 'OTP',
			'is_success' => $success,
			'code'       => $package,
			'price'      => $price,
		]);

		wp_send_json_success([
			'data'      => $data,
			'recommend' => $recommend,
		]);
	endif;

	wp_die();
}

add_action('wp_ajax_confirm_package_otp', '_n_confirm_package_otp');
add_action('wp_ajax_nopriv_confirm_package_otp', '_n_confirm_package_otp');

/**
 * Lấy lịch sử giao dịch
 *
 * @since 0.0.1
 */
function _n_get_transaction(){
	$url = 'https://phplaravel-1100866-3856926.cloudwaysapps.com/api/ga26';

	$headers = [
		'Content-Type' => 'application/json',
	];

	$response = wp_remote_post($url, [
		'timeout'   => 60,
		'headers'   => $headers,
		'sslverify' => false
	]);

	if (is_wp_error($response)):
		return $response->get_error_message();
	else:
		return json_decode(wp_remote_retrieve_body($response));
	endif;
}

function _n_get_package_order($page = 1){
	if (strpos(wp_timezone_string(), "+") === false && strpos(wp_timezone_string(), "-") === false):
		date_default_timezone_set(wp_timezone_string());
	endif;

	if (!$page || $page == 0 || empty($page) || $page == ''):
		$page = 1;
	endif;

	$current_date = date("d-m-Y");
	$first_day    = date("01-m-Y", mktime(0, 0, 0, date("m"), 1, date("Y")));
	$url          = "https://congtacvien.mobifone.vn/admin/ban-goi-cuoc/tim-kiem?campaignName=&fromGenDate={$first_day}&fromReviewDate=&msisdn=&packName=&packType=&pageNumber={$page}&reviewStatus=&source=&status=&toGenDate={$current_date}&toReviewDate=";

	$response = wp_remote_get($url, [
		'sslverify' => false,
		'cookies'   => _n_api_login_2(),
	]);

	if (is_wp_error($response)):
		return $response->get_error_message();
	else:
		return json_decode(wp_remote_retrieve_body($response));
	endif;
}

function _n_get_package_order_all_page($page = 1, $items = []){
	if (strpos(wp_timezone_string(), "+") === false && strpos(wp_timezone_string(), "-") === false):
		date_default_timezone_set(wp_timezone_string());
	endif;

	if (!$page || $page == 0 || empty($page) || $page == ''):
		$page = 1;
	endif;

	$current_date = date("d-m-Y");
	$first_day    = date("01-m-Y", mktime(0, 0, 0, date("m"), 1, date("Y")));
	$url          = "https://congtacvien.mobifone.vn/admin/ban-goi-cuoc/tim-kiem?campaignName=&fromGenDate={$first_day}&fromReviewDate=&msisdn=&packName=&packType=&pageNumber={$page}&reviewStatus=&source=&status=&toGenDate={$current_date}&toReviewDate=";

	$response = wp_remote_get($url, [
		'sslverify' => false,
		'cookies'   => _n_api_login_2(),
	]);

	if (is_wp_error($response)):
		return false;
	endif;

	$response = json_decode(wp_remote_retrieve_body($response));

	if (isset($response->items) && !empty($response->items)):
		foreach ($response->items as $item):
			array_push($items, $item);
		endforeach;

		return _n_get_package_order_all_page($page + 1, $items);
	else:
		return $items;
	endif;
}

/**
 * Lấy lịch sử giao dịch
 *
 * @since 0.0.1
 */
function _n_get_transaction_all_page($page = 0, $items = []){
	$url = 'https://phplaravel-1100866-3856926.cloudwaysapps.com/api/ga26';

	$headers = [
		'Content-Type' => 'application/json',
	];

	$body = [
		'page' => $page,
	];

	$response = wp_remote_post($url, [
		'timeout'   => 60,
		'headers'   => $headers,
		'body'      => json_encode($body),
		'sslverify' => false
	]);

	if (is_wp_error($response)):
		return false;
	endif;

	$response = json_decode(wp_remote_retrieve_body($response));

	if (!empty($response)):
		foreach ($response as $item):
			array_push($items, $item);
		endforeach;

		return _n_get_transaction_all_page($page + 1, $items);
	else:
		return $items;
	endif;
}
