<?php
/**
 * N Framework
 *
 * WARNING: This file is part of the core N Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @since      0.0.1
 * @package    N
 * @subpackage N/lib/functions
 */

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

if (!defined('ABSPATH')):
	exit; // Exit if accessed directly.
endif;

/**
 * Đăng ký custom post type gói cước
 *
 * @since 0.0.1
 */
function _n_register_package_post_type(){
	$labels = [
		'name'                  => _x('Gói cước', 'Post Type General Name', '_n'),
		'singular_name'         => _x('Gói cước', 'Post Type Singular Name', '_n'),
		'menu_name'             => __('Gói cước', '_n'),
		'name_admin_bar'        => __('Post Type', '_n'),
		'archives'              => __('Item Archives', '_n'),
		'attributes'            => __('Item Attributes', '_n'),
		'parent_item_colon'     => __('Parent Item:', '_n'),
		'all_items'             => __('All Items', '_n'),
		'add_new_item'          => __('Add New Item', '_n'),
		'add_new'               => __('Add New', '_n'),
		'new_item'              => __('New Item', '_n'),
		'edit_item'             => __('Edit Item', '_n'),
		'update_item'           => __('Update Item', '_n'),
		'view_item'             => __('View Item', '_n'),
		'view_items'            => __('View Items', '_n'),
		'search_items'          => __('Search Item', '_n'),
		'not_found'             => __('Not found', '_n'),
		'not_found_in_trash'    => __('Not found in Trash', '_n'),
		'featured_image'        => __('Featured Image', '_n'),
		'set_featured_image'    => __('Set featured image', '_n'),
		'remove_featured_image' => __('Remove featured image', '_n'),
		'use_featured_image'    => __('Use as featured image', '_n'),
		'insert_into_item'      => __('Insert into item', '_n'),
		'uploaded_to_this_item' => __('Uploaded to this item', '_n'),
		'items_list'            => __('Items list', '_n'),
		'items_list_navigation' => __('Items list navigation', '_n'),
		'filter_items_list'     => __('Filter items list', '_n'),
	];

	$rewrite = [
		'slug'       => 'goi-cuoc',
		'with_front' => true,
		'pages'      => true,
		'feeds'      => true,
	];

	$args = [
		'label'               => __('Gói cước', '_n'),
		'description'         => __('Post Type Description', '_n'),
		'labels'              => $labels,
		'supports'            => ['title', 'editor', 'thumbnail'],
		'taxonomies'          => [],
		'hierarchical'        => false,
		'public'              => true,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'menu_position'       => 5,
		'show_in_admin_bar'   => true,
		'show_in_nav_menus'   => true,
		'can_export'          => true,
		'has_archive'         => true,
		'exclude_from_search' => false,
		'publicly_queryable'  => true,
		'rewrite'             => $rewrite,
		'capability_type'     => 'page',
	];

	register_post_type('package', $args);
}

add_action('init', '_n_register_package_post_type', 0);

/**
 * Đăng ký custom post type client data
 *
 * @since 0.0.1
 */
function _n_register_client_data_post_type(){
	$labels = [
		'name'                  => _x('Dữ liệu người dùng', 'Post Type General Name', '_n'),
		'singular_name'         => _x('Dữ liệu người dùng', 'Post Type Singular Name', '_n'),
		'menu_name'             => __('Dữ liệu người dùng', '_n'),
		'name_admin_bar'        => __('Dữ liệu người dùng', '_n'),
		'archives'              => __('Item Archives', '_n'),
		'attributes'            => __('Item Attributes', '_n'),
		'parent_item_colon'     => __('Parent Item:', '_n'),
		'all_items'             => __('All Items', '_n'),
		'add_new_item'          => __('Add New Item', '_n'),
		'add_new'               => __('Add New', '_n'),
		'new_item'              => __('New Item', '_n'),
		'edit_item'             => __('Edit Item', '_n'),
		'update_item'           => __('Update Item', '_n'),
		'view_item'             => __('View Item', '_n'),
		'view_items'            => __('View Items', '_n'),
		'search_items'          => __('Search Item', '_n'),
		'not_found'             => __('Not found', '_n'),
		'not_found_in_trash'    => __('Not found in Trash', '_n'),
		'featured_image'        => __('Featured Image', '_n'),
		'set_featured_image'    => __('Set featured image', '_n'),
		'remove_featured_image' => __('Remove featured image', '_n'),
		'use_featured_image'    => __('Use as featured image', '_n'),
		'insert_into_item'      => __('Insert into item', '_n'),
		'uploaded_to_this_item' => __('Uploaded to this item', '_n'),
		'items_list'            => __('Items list', '_n'),
		'items_list_navigation' => __('Items list navigation', '_n'),
		'filter_items_list'     => __('Filter items list', '_n'),
	];

	$args = [
		'label'               => __('Dữ liệu người dùng', '_n'),
		'description'         => __('Post Type Description', '_n'),
		'labels'              => $labels,
		'supports'            => ['title'],
		'hierarchical'        => true,
		'public'              => true,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'menu_position'       => 5,
		'menu_icon'           => 'dashicons-database',
		'show_in_admin_bar'   => true,
		'show_in_nav_menus'   => true,
		'can_export'          => true,
		'has_archive'         => false,
		'exclude_from_search' => true,
		'publicly_queryable'  => true,
		'capability_type'     => 'page',
	];

	register_post_type('client_data', $args);
}

add_action('init', '_n_register_client_data_post_type', 0);

/**
 * Đăng ký custom post type client data
 *
 * @since 0.0.1
 */
function _n_register_package_order_post_type(){
	$labels = [
		'name'                  => _x('Đơn hàng', 'Post Type General Name', '_n'),
		'singular_name'         => _x('Đơn hàng', 'Post Type Singular Name', '_n'),
		'menu_name'             => __('Đơn hàng', '_n'),
		'name_admin_bar'        => __('Đơn hàng', '_n'),
		'archives'              => __('Item Archives', '_n'),
		'attributes'            => __('Item Attributes', '_n'),
		'parent_item_colon'     => __('Parent Item:', '_n'),
		'all_items'             => __('All Items', '_n'),
		'add_new_item'          => __('Add New Item', '_n'),
		'add_new'               => __('Add New', '_n'),
		'new_item'              => __('New Item', '_n'),
		'edit_item'             => __('Edit Item', '_n'),
		'update_item'           => __('Update Item', '_n'),
		'view_item'             => __('View Item', '_n'),
		'view_items'            => __('View Items', '_n'),
		'search_items'          => __('Search Item', '_n'),
		'not_found'             => __('Not found', '_n'),
		'not_found_in_trash'    => __('Not found in Trash', '_n'),
		'featured_image'        => __('Featured Image', '_n'),
		'set_featured_image'    => __('Set featured image', '_n'),
		'remove_featured_image' => __('Remove featured image', '_n'),
		'use_featured_image'    => __('Use as featured image', '_n'),
		'insert_into_item'      => __('Insert into item', '_n'),
		'uploaded_to_this_item' => __('Uploaded to this item', '_n'),
		'items_list'            => __('Items list', '_n'),
		'items_list_navigation' => __('Items list navigation', '_n'),
		'filter_items_list'     => __('Filter items list', '_n'),
	];

	$args = [
		'label'               => __('Đơn hàng', '_n'),
		'description'         => __('Post Type Description', '_n'),
		'labels'              => $labels,
		'supports'            => ['title'],
		'hierarchical'        => true,
		'public'              => true,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'menu_position'       => 5,
		'menu_icon'           => 'dashicons-list-view',
		'show_in_admin_bar'   => true,
		'show_in_nav_menus'   => true,
		'can_export'          => true,
		'has_archive'         => false,
		'exclude_from_search' => true,
		'publicly_queryable'  => true,
		'capability_type'     => 'page',
	];

	register_post_type('package_order', $args);
}

add_action('init', '_n_register_package_order_post_type', 0);

/**
 * Thêm cột tuỳ chỉnh vào admin
 */
function _n_client_data_column_heading($columns){
	$columns['client_data_action'] = 'Hành động';
	$columns['client_data_phone']  = 'Số điện thoại';

	return $columns;
}

add_filter('manage_edit-client_data_columns', '_n_client_data_column_heading', 10);

/**
 * Nội dung cột
 */
function _n_client_data_column_content($column, $post_id){
	$client_data_phone  = get_post_meta($post_id, '_client_data_phone', true);
	$client_data_action = get_post_meta($post_id, '_client_data_action', true);

	if ($column === 'client_data_action' && $client_data_action != ''):
		echo $client_data_action;
	endif;

	if ($column === 'client_data_phone' && $client_data_phone != ''):
		echo $client_data_phone;
	endif;
}

add_action('manage_client_data_posts_custom_column', '_n_client_data_column_content', 10, 2);

function _n_package_order_admin_order($wp_query){
	if (is_admin() && !isset($_GET['orderby'])):
		$post_type = $wp_query->query['post_type'];
		if (in_array($post_type, ['package_order'])):
			$wp_query->set('orderby', 'date');
			$wp_query->set('order', 'DESC');
		endif;
	endif;
}

add_filter('pre_get_posts', '_n_package_order_admin_order');

/**
 *
 */
function _n_restrict_manage_posts(){
	if (!is_admin()):
		return;
	endif;

	global $wpdb, $table_prefix;

	$post_type      = isset($_GET['post_type']) ? strval($_GET['post_type']) : false;

	if (!$post_type):
		return;
	endif;

	if ($post_type == 'package_order'):
		$phone = $_GET['phone'] ?? '';
		$package    = $_GET['package_code'] ?? '';
		$channel    = $_GET['channel'] ?? '';
		$status     = $_GET['status'] ?? '';
		$date_start = $_GET['date_start'] ?? date("Y-m-01", mktime(0, 0, 0, date("m"), 1, date("Y")));
		$date_end   = $_GET['date_end'] ?? date("Y-m-d");

		?>
		<input type="date" class="n-input" name="date_start" value="<?= $date_start ?>" placeholder="Từ ngày" aria-label="Từ ngày">

		<input type="date" class="n-input" name="date_end" value="<?= $date_end ?>" placeholder="Đến ngày" aria-label="Đến ngày">

		<input type="text" class="n-input" name="phone" value="<?= $phone ?>" placeholder="Số điện thoại" aria-label="Số điện thoại">

		<input type="text" class="n-input" name="package_code" value="<?= $package ?>" placeholder="Gói cước" aria-label="Gói cước">

		<select name="channel" aria-label="Kênh">
			<option selected="selected" value="" <?php selected($channel, ''); ?>>Kênh</option>
			<option value="otp" <?php selected($channel, 'otp'); ?>>OTP</option>
			<option value="sms" <?php selected($channel, 'sms'); ?>>SMS</option>
		</select>

		<select name="status" aria-label="Trạng thái">
			<option selected="selected" value="" <?php selected($status, ''); ?>>Trạng thái</option>
			<option value="complete" <?php selected($status, 'complete'); ?>>Hoàn thành</option>
			<option value="fail" <?php selected($status, 'fail'); ?>>Thất bại</option>
		</select>

		<input type="submit" name="export" class="button" value="Xuất excel">

	<?php endif;
	if ($post_type == 'cashback'):
		$phone = $_GET['phone'] ?? '';
		$status     = $_GET['status'] ?? '';
		$date_start = $_GET['date_start'] ?? date("Y-m-01", mktime(0, 0, 0, date("m"), 1, date("Y")));
		$date_end   = $_GET['date_end'] ?? date("Y-m-d");

		?>
		<input type="date" class="n-input" name="date_start" value="<?= $date_start ?>" placeholder="Từ ngày" aria-label="Từ ngày">

		<input type="date" class="n-input" name="date_end" value="<?= $date_end ?>" placeholder="Đến ngày" aria-label="Đến ngày">

		<input type="text" class="n-input" name="phone" value="<?= $phone ?>" placeholder="Số điện thoại" aria-label="Số điện thoại">

		<select name="status" aria-label="Trạng thái">
			<option selected="selected" value="" <?php selected($status, ''); ?>>Trạng thái</option>
			<option value="processing" <?php selected($status, 'processing'); ?>>Đang xử lý</option>
			<option value="success" <?php selected($status, 'success'); ?>>Thành công</option>
		</select>

		<input type="submit" name="export" class="button" value="Xuất excel">
	<?php endif;
}

add_action('restrict_manage_posts', '_n_restrict_manage_posts');

/**
 *
 */
function _n_cashback_filter_request($query){
	if (is_admin() && isset($_GET['post_type']) && $_GET['post_type'] == 'cashback'):
		$phone      = $_GET['phone'] ?? false;
		$status     = $_GET['status'] ?? false;
		$date_start = $_GET['date_start'] ?? false;
		$date_end   = $_GET['date_end'] ?? false;

		if ($phone && $phone != ''):
			$meta_query[] = [
				'key'     => '_cashback_phone',
				'value'   => $phone,
				'compare' => 'LIKE',
			];
		endif;

		if ($status && $status != ''):
			$meta_query[] = [
				'key'     => '_cashback_status',
				'value'   => $status,
				'compare' => '=',
			];
		endif;

		if ($date_start && $date_end):
			$meta_query[] = [
				'key'     => '_cashback_package_date',
				'value'   => [$date_start, $date_end],
				'type'    => 'DATE',
				'compare' => 'BETWEEN',
			];
		endif;

		$meta_query['relation'] = 'AND';
		$query->set('meta_query', $meta_query);
	endif;
}

add_filter('parse_query', '_n_cashback_filter_request');

/**
 *
 */
function _n_package_order_filter_request($query){
	if (is_admin() && isset($_GET['post_type']) && $_GET['post_type'] == 'package_order'):
		$phone      = $_GET['phone'] ?? false;
		$package    = $_GET['package_code'] ?? false;
		$channel    = $_GET['channel'] ?? false;
		$status     = $_GET['status'] ?? false;
		$date_start = $_GET['date_start'] ?? false;
		$date_end   = $_GET['date_end'] ?? false;

		if ($phone && $phone != ''):
			$meta_query[] = [
				'key'     => '_package_order_phone_number',
				'value'   => $phone,
				'compare' => 'LIKE',
			];
		endif;

		if ($package && $package != ''):
			$meta_query[] = [
				'key'     => '_package_order_pack',
				'value'   => $package,
				'compare' => '=',
			];
		endif;

		if ($channel && $channel != ''):
			$meta_query[] = [
				'key'     => '_package_order_channel',
				'value'   => $channel,
				'compare' => '=',
			];
		endif;

		if ($status && $status != ''):
			if ($status == 'complete'):
				$meta_query[] = [
					'key'     => '_package_order_status',
					'value'   => '0',
					'compare' => '!=',
				];
			else:
				$meta_query[] = [
					'key'     => '_package_order_status',
					'value'   => '0',
					'compare' => '=',
				];
			endif;
		endif;

		if ($date_start && $date_end):
			$meta_query[] = [
				'key'     => '_package_order_date',
				'value'   => [$date_start, $date_end],
				'type'    => 'DATE',
				'compare' => 'BETWEEN',
			];
		endif;

		$meta_query['relation'] = 'AND';
		$query->set('meta_query', $meta_query);
	endif;
}

add_filter('parse_query', '_n_package_order_filter_request');

/**
 *
 */
function _n_package_order_export(){
	if (is_admin() && isset($_GET['post_type']) && $_GET['post_type'] == 'package_order'):
		$phone      = $_GET['phone'] ?? false;
		$package    = $_GET['package_code'] ?? false;
		$channel    = $_GET['channel'] ?? false;
		$status     = $_GET['status'] ?? false;
		$date_start = $_GET['date_start'] ?? false;
		$date_end   = $_GET['date_end'] ?? false;
		$export     = $_GET['export'] ?? false;

		if (!$export):
			return;
		endif;

		if ($phone && $phone != ''):
			$meta_query[] = [
				'key'     => '_package_order_phone_number',
				'value'   => $phone,
				'compare' => '=',
			];
		endif;

		if ($package && $package != ''):
			$meta_query[] = [
				'key'     => '_package_order_pack',
				'value'   => $package,
				'compare' => '=',
			];
		endif;

		if ($channel && $channel != ''):
			$meta_query[] = [
				'key'     => '_package_order_channel',
				'value'   => $channel,
				'compare' => '=',
			];
		endif;

		if ($status && $status != ''):
			if ($status == 'complete'):
				$meta_query[] = [
					'key'     => '_package_order_status',
					'value'   => '0',
					'compare' => '!=',
				];
			else:
				$meta_query[] = [
					'key'     => '_package_order_status',
					'value'   => '0',
					'compare' => '=',
				];
			endif;
		endif;

		if ($date_start && $date_end):
			$meta_query[] = [
				'key'     => '_package_order_date',
				'value'   => [$date_start, $date_end],
				'type'    => 'DATE',
				'compare' => 'BETWEEN',
			];
		endif;

		$meta_query['relation'] = 'AND';

		$args = [
			'post_type'      => 'package_order',
			'post_status'    => 'publish',
			'posts_per_page' => - 1,
			'meta_query'     => $meta_query,
		];

		$loop = new WP_Query($args);

		if ($loop->have_posts()):
			$spreadsheet = new Spreadsheet();
			$sheet       = $spreadsheet->getActiveSheet();
			$data        = [];
			array_push($data, ['SĐT', 'Code', 'Kênh', 'Giá', 'Hoa hồng', 'Thời gian', 'Trạng thái', 'Mô tả']);

			while ($loop->have_posts()):
				$loop->the_post();
				$package_order_id = get_the_ID();

				$phone       = get_post_meta($package_order_id, '_package_order_phone_number', true);
				$package     = get_post_meta($package_order_id, '_package_order_pack', true);
				$channel     = get_post_meta($package_order_id, '_package_order_channel', true);
				$price       = get_post_meta($package_order_id, '_package_order_price', true);
				$revenue     = get_post_meta($package_order_id, '_package_order_revenue', true);
				$date        = get_post_meta($package_order_id, '_package_order_date', true);
				$status      = get_post_meta($package_order_id, '_package_order_status', true);
				$description = get_post_meta($package_order_id, '_package_order_description', true);

				array_push($data, [
					$phone,
					$package,
					$channel,
					$price,
					$revenue,
					$date,
					$status == '0' ? 'Thất bại' : ' Thành công',
					$description,
				]);
			endwhile;

			$sheet->fromArray($data, null, 'A1');
			$writer = new Xlsx($spreadsheet);
			header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
			header('Content-Disposition: attachment;filename="package-order-export-' . date("d-m-Y-H:i:s") . '.xlsx"');
			header('Cache-Control: max-age=0');
			$writer->save('php://output');
		endif;
	endif;
}

add_filter('admin_init', '_n_package_order_export');

/**
 *
 */
function _n_cashback_export(){
	if (is_admin() && isset($_GET['post_type']) && $_GET['post_type'] == 'cashback'):
		$export     = $_GET['export'] ?? false;
		$phone      = $_GET['phone'] ?? false;
		$status     = $_GET['status'] ?? false;
		$date_start = $_GET['date_start'] ?? false;
		$date_end   = $_GET['date_end'] ?? false;

		if (!$export):
			return;
		endif;

		if ($phone && $phone != ''):
			$meta_query[] = [
				'key'     => '_cashback_phone',
				'value'   => $phone,
				'compare' => '=',
			];
		endif;

		if ($status && $status != ''):
			$meta_query[] = [
				'key'     => '_cashback_status',
				'value'   => $status,
				'compare' => '=',
			];
		endif;

		if ($date_start && $date_end):
			$meta_query[] = [
				'key'     => '_cashback_package_date',
				'value'   => [$date_start, $date_end],
				'type'    => 'DATE',
				'compare' => 'BETWEEN',
			];
		endif;

		$meta_query['relation'] = 'AND';

		$args = [
			'post_type'      => 'cashback',
			'post_status'    => 'publish',
			'posts_per_page' => - 1,
			'meta_query'     => $meta_query,
		];

		$loop = new WP_Query($args);

		if ($loop->have_posts()):
			$spreadsheet = new Spreadsheet();
			$sheet       = $spreadsheet->getActiveSheet();
			$data        = [];
			array_push($data, ['ID', 'SĐT', 'CODE', 'NGÀY ĐĂNG KÝ', 'TIỀN HOÀN', 'HOÀN THỰC', 'HOÀN CÒN LẠI']);

			while ($loop->have_posts()):
				$loop->the_post();
				$package_order_id = get_the_ID();

				$phone             = get_post_meta($package_order_id, '_cashback_phone', true);
				$package           = get_post_meta($package_order_id, '_cashback_package', true);
				$package_date      = get_post_meta($package_order_id, '_cashback_package_date', true);
				$amount            = get_post_meta($package_order_id, '_cashback_amount', true);
				$amount_real       = get_post_meta($package_order_id, '_cashback_amount_real', true);
				$amount_processing = get_post_meta($package_order_id, '_cashback_amount_processing', true);

				array_push($data, [
					$package_order_id,
					$phone,
					$package,
					$package_date,
					$amount,
					$amount_real,
					$amount_processing
				]);
			endwhile;

			$sheet->fromArray($data, null, 'A1');
			$writer = new Xlsx($spreadsheet);
			header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
			header('Content-Disposition: attachment;filename="cashback-export-' . date("d-m-Y-H:i:s") . '.xlsx"');
			header('Cache-Control: max-age=0');
			$writer->save('php://output');
		endif;
	endif;
}

add_filter('admin_init', '_n_cashback_export');

/**
 *
 */
function _n__remove_date_filter($months){
	global $typenow;
	if ($typenow == 'package_order' || $typenow == 'cashback'):
		return [];
	endif;

	return $months;
}

add_filter('months_dropdown_results', '_n__remove_date_filter');

/**
 * Thêm cột tuỳ chỉnh vào admin
 */
function _n_package_order_column_heading($columns){
	$columns['phone']    = 'SĐT';
	$columns['package']  = 'Code';
	$columns['channel']  = 'Kênh';
	$columns['price']    = 'Giá';
	$columns['revenue']  = 'Hoa hồng';
	$columns['reg_date'] = 'Thời gian';
	$columns['status']   = 'Trạng thái';
	$columns['desc']     = 'Mô tả';

	unset($columns['date']);

	return $columns;
}

add_filter('manage_edit-package_order_columns', '_n_package_order_column_heading', 10);

/**
 * Thêm cột tuỳ chỉnh vào admin
 */
function _n_cashback_column_heading($columns){
	$columns['phone']               = 'SĐT';
	$columns['package']             = 'Code';
	$columns['reg_date']            = 'Ngày đăng ký';
	$columns['cashback']            = 'Tiền hoàn';
	$columns['cashback_real']       = 'Tiền đã hoàn';
	$columns['cashback_processing'] = 'Tiền chưa hoàn';
	$columns['status']              = 'Trạng thái';
	$columns['cashback_date']       = 'Ngày hoàn';

	unset($columns['date']);

	return $columns;
}

add_filter('manage_edit-cashback_columns', '_n_cashback_column_heading', 10);

/**
 * Nội dung cột
 */
function _n_package_order_column_content($column, $post_id){
	$phone       = get_post_meta($post_id, '_package_order_phone_number', true);
	$package     = get_post_meta($post_id, '_package_order_pack', true);
	$channel     = get_post_meta($post_id, '_package_order_channel', true);
	$price       = get_post_meta($post_id, '_package_order_price', true);
	$revenue     = get_post_meta($post_id, '_package_order_revenue', true);
	$date        = get_post_meta($post_id, '_package_order_date', true);
	$status      = get_post_meta($post_id, '_package_order_status', true);
	$description = get_post_meta($post_id, '_package_order_description', true);

	if ($column === 'phone'):
		echo $phone;
	endif;

	if ($column === 'package'):
		echo $package;
	endif;

	if ($column === 'channel'):
		echo $channel;
	endif;

	if ($column === 'price'):
		echo number_format($price, 0, '.', '.') . "đ";
	endif;

	if ($column === 'revenue'):
		echo number_format($revenue, 0, '.', '.') . "đ";
	endif;

	if ($column === 'reg_date'):
		echo date('d/m/Y H:i:s', strtotime($date));
	endif;

	if ($column === 'status'):
		echo $status == '0' ? 'Thất bại' : ' Thành công';
	endif;

	if ($column === 'desc'):
		echo $description;
	endif;
}

add_action('manage_package_order_posts_custom_column', '_n_package_order_column_content', 10, 2);

/**
 * Nội dung cột
 */
function _n_cashback_column_content($column, $post_id){
	$phone               = get_post_meta($post_id, '_cashback_phone', true);
	$package             = get_post_meta($post_id, '_cashback_package', true);
	$cashback            = get_post_meta($post_id, '_cashback_amount', true);
	$cashback_processing = get_post_meta($post_id, '_cashback_amount_processing', true);
	$cashback_real       = get_post_meta($post_id, '_cashback_amount_real', true);
	$date                = get_post_meta($post_id, '_cashback_package_date', true);
	$status              = get_post_meta($post_id, '_cashback_status', true);
	$cashback_date       = get_post_meta($post_id, '_cashback_date', true);

	if ($column === 'phone'):
		echo $phone;
	endif;

	if ($column === 'package'):
		echo $package;
	endif;

	if ($column === 'reg_date'):
		echo $date;
	endif;

	if ($column === 'cashback'):
		if (!is_numeric($cashback)):
			$cashback = 0;
		endif;

		echo number_format($cashback, 0, '.', '.') . "đ";
	endif;

	if ($column === 'cashback_real'):
		if (!is_numeric($cashback_real)):
			$cashback_real = 0;
		endif;

		echo number_format($cashback_real, 0, '.', '.') . "đ";
	endif;

	if ($column === 'cashback_processing'):
		if (!is_numeric($cashback_processing)):
			$cashback_processing = 0;
		endif;

		echo number_format($cashback_processing, 0, '.', '.') . "đ";
	endif;

	if ($column === 'status'):
		echo $status == 'processing' ? 'Đang xử lý' : ' Thành công';
	endif;

	if ($column === 'cashback_date'):
		echo $cashback_date;
	endif;
}

add_action('manage_cashback_posts_custom_column', '_n_cashback_column_content', 10, 2);

/**
 * Đăng ký custom post type cashback
 *
 * @since 0.0.1
 */
function _n_register_cashback_post_type(){
	$labels = [
		'name'                  => _x('Hoàn tiền', 'Post Type General Name', '_n'),
		'singular_name'         => _x('Hoàn tiền', 'Post Type Singular Name', '_n'),
		'menu_name'             => __('Hoàn tiền', '_n'),
		'name_admin_bar'        => __('Hoàn tiền', '_n'),
		'archives'              => __('Item Archives', '_n'),
		'attributes'            => __('Item Attributes', '_n'),
		'parent_item_colon'     => __('Parent Item:', '_n'),
		'all_items'             => __('All Items', '_n'),
		'add_new_item'          => __('Add New Item', '_n'),
		'add_new'               => __('Add New', '_n'),
		'new_item'              => __('New Item', '_n'),
		'edit_item'             => __('Edit Item', '_n'),
		'update_item'           => __('Update Item', '_n'),
		'view_item'             => __('View Item', '_n'),
		'view_items'            => __('View Items', '_n'),
		'search_items'          => __('Search Item', '_n'),
		'not_found'             => __('Not found', '_n'),
		'not_found_in_trash'    => __('Not found in Trash', '_n'),
		'featured_image'        => __('Featured Image', '_n'),
		'set_featured_image'    => __('Set featured image', '_n'),
		'remove_featured_image' => __('Remove featured image', '_n'),
		'use_featured_image'    => __('Use as featured image', '_n'),
		'insert_into_item'      => __('Insert into item', '_n'),
		'uploaded_to_this_item' => __('Uploaded to this item', '_n'),
		'items_list'            => __('Items list', '_n'),
		'items_list_navigation' => __('Items list navigation', '_n'),
		'filter_items_list'     => __('Filter items list', '_n'),
	];

	$args = [
		'label'               => __('Hoàn tiền', '_n'),
		'description'         => __('Post Type Description', '_n'),
		'labels'              => $labels,
		'supports'            => ['title'],
		'hierarchical'        => true,
		'public'              => true,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'menu_position'       => 5,
		'menu_icon'           => 'dashicons-money-alt',
		'show_in_admin_bar'   => true,
		'show_in_nav_menus'   => true,
		'can_export'          => true,
		'has_archive'         => false,
		'exclude_from_search' => true,
		'publicly_queryable'  => true,
		'capability_type'     => 'page',
	];

	register_post_type('cashback', $args);
}

add_action('init', '_n_register_cashback_post_type', 0);
