<?php
/**
 * N Framework
 *
 * WARNING: This file is part of the core N Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @since      0.0.1
 * @package    N
 * @subpackage N/lib/functions
 */

if (!defined('ABSPATH')):
	exit; // Exit if accessed directly.
endif;

/**
 * Enqueue scripts and styles.
 *
 * @since    0.0.1
 */
function _n_load_scripts(){
	$theme_version   = wp_get_theme()->get('Version');
	$register_syntax = get_option('options__theme_general_settings__syntax__register__syntax', '');
	$register_send   = get_option('options__theme_general_settings__syntax__register__send', '');

	// Include jquery
	wp_enqueue_script('jquery');

	if ((!is_admin()) && is_singular() && comments_open() && get_option('thread_comments')):
		wp_enqueue_script('comment-reply');
	endif;

	wp_enqueue_style('_n-bootstrap', get_theme_file_uri('assets/libs/bootstrap/css/bootstrap.min.css'), [], $theme_version, 'all');
	wp_enqueue_style('_n-slick', get_theme_file_uri('assets/libs/slick/slick.css'), [], $theme_version, 'all');
	wp_enqueue_style('_n-fontawesome', get_theme_file_uri('assets/libs/fontawesome/css/all.min.css'), [], $theme_version, 'all');
	wp_enqueue_style('_n-fancybox', get_theme_file_uri('assets/libs/fancybox/jquery.fancybox.css'), [], $theme_version, 'all');
	wp_enqueue_style('_n-framework', get_theme_file_uri('assets/css/style.css'), [], $theme_version, 'all');

	wp_enqueue_script('_n-bootstrap', get_theme_file_uri('assets/libs/bootstrap/js/bootstrap.bundle.min.js'), [], $theme_version, true);
	wp_enqueue_script('_n-slicknav', get_theme_file_uri('assets/libs/slicknav/jquery.slicknav.js'), ['jquery'], $theme_version, true);
	wp_enqueue_script('_n-slick', get_theme_file_uri('assets/libs/slick/slick.js'), [], $theme_version, true);
	wp_enqueue_script('_n-fancybox', get_theme_file_uri('assets/libs/fancybox/jquery.fancybox.js'), [], $theme_version, true);
	wp_enqueue_script('_n-jquery-ui', get_theme_file_uri('assets/js/jquery-ui.js'), [], $theme_version, true);
	wp_enqueue_script('_n-jquery-ui-touch-punch', get_theme_file_uri('assets/js/jquery.ui.touch-punch.min.js'), [], $theme_version, true);
	wp_enqueue_script('_n-framework', get_theme_file_uri('assets/js/script.js'), ['jquery'], $theme_version, true);
	wp_localize_script('_n-framework', '_n_framework', [
		'admin_ajax_url'  => admin_url('admin-ajax.php'),
		'register_syntax' => $register_syntax,
		'register_send'   => $register_send,
	]);
}

add_action('wp_enqueue_scripts', '_n_load_scripts');
