<?php
/**
 * N Framework
 *
 * WARNING: This file is part of the core N Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @since      0.0.1
 * @package    N
 * @subpackage N/lib/functions
 */

if (!defined('ABSPATH')):
	exit; // Exit if accessed directly.
endif;

function _n_fb_sdk(){
	?>
	<div id="fb-root"></div>
	<script async defer crossorigin="anonymous" src="https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v18.0&appId=27969104193041014" nonce="MPuh4F8H"></script>
	<!-- Google tag (gtag.js) -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-SNCM2JJMZX"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'G-SNCM2JJMZX');
	</script>
	<?php
}

/**
 * Get loadert template
 *
 * @since 0.0.1
 */
function _n_get_template_loader(){
	get_template_part('template-parts/loader');
}

/**
 * Get header template
 *
 * @since 0.0.1
 */
function _n_get_template_header(){
	get_template_part('template-parts/header');
}

/**
 * Get footer template
 *
 * @since 0.0.1
 */
function _n_get_template_footer(){
	get_template_part('template-parts/footer');
}

/**
 * Get single package template
 *
 * @since 0.0.1
 */
function _n_get_template_single_package(){
	get_template_part('template-parts/single-package');
}

/**
 * Get slider template
 *
 * @since 0.0.1
 */
function _n_get_template_slider(){
	get_template_part('template-parts/slider');
}

/**
 * Get slider template
 *
 * @since 0.0.1
 */
function _n_get_template_vina_slider(){
	get_template_part('template-parts/vina-slider');
}

/**
 * Get advanced search template
 *
 * @since 0.0.1
 */
function _n_get_template_advanced_search(){
	get_template_part('template-parts/advanced-search');
}

/**
 * Get advanced search template
 *
 * @since 0.0.1
 */
function _n_get_template_vina_advanced_search(){
	get_template_part('template-parts/vina-advanced-search');
}

/**
 * Get search package template
 *
 * @since 0.0.1
 */
function _n_get_template_search_package(){
	get_template_part('template-parts/search-package');
}

/**
 * Get search package recommend
 *
 * @since 0.0.1
 */
function _n_get_template_package_recommend(){
	get_template_part('template-parts/package-recommend');
}

/**
 * Get packages template
 *
 * @since 0.0.1
 */
function _n_get_template_packages(){
	get_template_part('template-parts/packages');
}

/**
 * Get packages template
 *
 * @since 0.0.1
 */
function _n_get_template_mno_menu(){
	get_template_part('template-parts/mno-menu');
}

/**
 * Get packages template
 *
 * @since 0.0.1
 */
function _n_get_template_vina_packages(){
	get_template_part('template-parts/vina-packages');
}

/**
 * Get modals template
 *
 * @since 0.0.1
 */
function _n_get_template_modals(){
	get_template_part('template-parts/modals');
}

/**
 * Get syntax template
 *
 * @since 0.0.1
 */
function _n_get_template_syntax(){
	get_template_part('template-parts/syntax');
}

/**
 * Get syntax template
 *
 * @since 0.0.1
 */
function _n_get_template_vina_syntax(){
	get_template_part('template-parts/vina-syntax');
}

/**
 * Get archive package template
 *
 * @since 0.0.1
 */
function _n_get_template_archive_package(){
	get_template_part('template-parts/archive-package');
}

/**
 * Get archive template
 *
 * @since 0.0.1
 */
function _n_get_template_archive(){
	get_template_part('template-parts/archive');
}

/**
 * Get single template
 *
 * @since 0.0.1
 */
function _n_get_template_single(){
	get_template_part('template-parts/single');
}

/**
 * Get recruitment template
 *
 * @since 0.0.1
 */
function _n_get_template_recruitment(){
	get_template_part('template-parts/recruitment');
}

/**
 * Get recruitment template
 *
 * @since 0.0.1
 */
function _n_get_template_about(){
	get_template_part('template-parts/about');
}

/**
 * Get fab template
 *
 * @since 0.0.1
 */
function _n_get_template_fab(){
	get_template_part('template-parts/fab');
}

/**
 * Get fab template
 *
 * @since 0.0.1
 */
function _n_get_template_fb(){
	get_template_part('template-parts/fb');
}

/**
 * Get cashback template
 *
 * @since 0.0.1
 */
function _n_get_template_cashback(){
	get_template_part('template-parts/cashback');
}

/**
 * Zalo OA
 *
 * @since 0.0.1
 */
function _n_zalo_oa(){
	?>
	<div class="zalo-chat-widget" data-oaid="4054682374558282299" data-welcome-message="Rất vui khi được hỗ trợ bạn!" data-autopopup="10" data-width="300" data-height="500"></div>
	<script src="https://sp.zalo.me/plugins/sdk.js"></script>
	<?php
}