<?php
/**
 * N Framework
 *
 * WARNING: This file is part of the core N Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @since      0.0.1
 * @package    N
 * @subpackage N/lib/functions
 */

if (!defined('ABSPATH')):
	exit; // Exit if accessed directly.
endif;

/**
 * Zalo OA
 *
 * @since 0.0.1
 */
add_action('wp_head', '_n_zalo_oa');
add_action('wp_head', '_n_fb_sdk');

/**
 * Loader templates
 *
 * @since 0.0.1
 */
add_action('_n_before_header', '_n_get_template_loader', 10);

/**
 * Header templates
 *
 * @since 0.0.1
 */
add_action('_n_header', '_n_get_template_header', 10);

/**
 * Landing templates
 *
 * @since 0.0.1
 */
//add_action('_n_front', '_n_get_template_mno_menu', 5);
add_action('_n_front', '_n_get_template_slider', 10);
add_action('_n_front', '_n_get_template_search_package', 20);
add_action('_n_front', '_n_get_template_advanced_search', 30);
add_action('_n_front', '_n_get_template_syntax', 40);
add_action('_n_front', '_n_get_template_packages', 50);

/**
 * Landing templates
 *
 * @since 0.0.1
 */
add_action('_n_page_template_page_templates_vina', '_n_get_template_mno_menu', 5);
add_action('_n_page_template_page_templates_vina', '_n_get_template_vina_slider', 10);
add_action('_n_page_template_page_templates_vina', '_n_get_template_vina_advanced_search', 20);
add_action('_n_page_template_page_templates_vina', '_n_get_template_vina_syntax', 30);
add_action('_n_page_template_page_templates_vina', '_n_get_template_vina_packages', 40);

/**
 * Archive package
 *
 * @since 0.0.1
 */
add_action('_n_search_package', '_n_get_template_archive_package', 10);
add_action('_n_archive_package', '_n_get_template_archive_package', 10);

/**
 * Archive
 *
 * @since 0.0.1
 */
add_action('_n_search', '_n_get_template_slider', 10);
add_action('_n_category', '_n_get_template_slider', 10);
add_action('_n_home', '_n_get_template_slider', 10);
add_action('_n_search', '_n_get_template_archive', 20);
add_action('_n_category', '_n_get_template_archive', 20);
add_action('_n_home', '_n_get_template_archive', 20);

/**
 * Footer templates
 *
 * @since 0.0.1
 */
add_action('_n_footer', '_n_get_template_fb', 10);
add_action('_n_footer', '_n_get_template_footer', 10);

/**
 * Single package templates
 *
 * @since 0.0.1
 */
add_action('_n_single_package', '_n_get_template_single_package', 10);

/**
 * Single templates
 *
 * @since 0.0.1
 */
add_action('_n_single_post', '_n_get_template_single', 10);
add_action('_n_single_page', '_n_get_template_single', 10);

/**
 * Recruitment templates
 *
 * @since 0.0.1
 */
add_action('_n_page_template_page_templates_recruitment', '_n_get_template_recruitment', 10);

/**
 * About templates
 *
 * @since 0.0.1
 */
add_action('_n_page_template_page_templates_about', '_n_get_template_about', 10);

/**
 * Cashback templates
 *
 * @since 0.0.1
 */
add_action('_n_page_template_page_templates_cashback', '_n_get_template_cashback', 10);

/**
 * Footer templates
 *
 * @since 0.0.1
 */
add_action('_n_after', '_n_get_template_modals', 10);
add_action('_n_after', '_n_get_template_fab', 20);
