<?php
/**
 * N Framework
 *
 * WARNING: This file is part of the core N Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @since      0.0.1
 * @package    N
 * @subpackage N/lib/admin
 */

if (!defined('ABSPATH')):
	exit; // Exit if accessed directly.
endif;

/**
 * Enqueue scripts and styles.
 *
 * @since 0.0.1
 */
function _n_admin_load_scripts(){
	$version = wp_get_theme('vienthongtaiphat')->get('Version');

	wp_enqueue_style('_n-framework-admin', get_theme_file_uri('assets/css/admin.css'), [], $version, 'all');

	wp_enqueue_script('_n-framework-admin', get_theme_file_uri('assets/js/admin.js'), ['jquery'], $version, true);
	wp_localize_script('_n-framework-admin', '_n_framework_admin', [
		'admin_ajax_url' => admin_url('admin-ajax.php'),
	]);
}

add_action('admin_enqueue_scripts', '_n_admin_load_scripts');
