<?php
/**
 * N Framework
 *
 * WARNING: This file is part of the core N Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @since      0.0.1
 * @cashback    N
 * @subcashback N/lib/admin
 */

if (!defined('ABSPATH')):
	exit; // Exit if accessed directly.
endif;

use Shuchkin\SimpleXLSX;

/**
 * Sim importer with ajax
 *
 * @since 0.0.1
 */
function _n_ajax_cashback_importer(){
	if (!(is_array($_POST) && is_array($_FILES) && defined('DOING_AJAX') && DOING_AJAX)):
		wp_send_json_error('Lỗi');
	endif;

	$file          = $_FILES['file'] ?? null;
	$start_row     = isset($_POST['start_row']) ? intval($_POST['start_row']) : 1;
	$batch_size    = 100;
	$end_row       = $start_row + $batch_size - 1;
	$imported_data = [];
	$status        = 'complete';

	if ($xlsx = SimpleXLSX::parse($file['tmp_name']) && $xlsx_rows = SimpleXLSX::parse($file['tmp_name'])->rows()):
		$count = count($xlsx_rows) - 1;

		if (!function_exists('post_exists')):
			require_once(ABSPATH . 'wp-admin/includes/post.php');
		endif;

		if ($start_row <= $count):
			$status = 'continue';
		endif;

		for ($row = $start_row; $row <= $end_row; $row ++):
			if ($row < 1):
				continue;
			endif;

			if (isset($xlsx_rows[$row])):
				$item        = $xlsx_rows[$row];
				$cashback_id = $item['0'];

				$cashback_exists = (new WP_Query(['post_type' => 'cashback', 'p' => $cashback_id]))->found_posts > 0;

				if (!$cashback_exists):
					continue;
				endif;

				$cashback_metas = [];

				$cashback_metas['_cashback_phone']             = $item['1'];
				$cashback_metas['_cashback_package']           = $item['2'];
				$cashback_metas['_cashback_amount']            = $item['4'];
				$cashback_metas['_cashback_amount_real']       = $item['5'];
				$cashback_metas['_cashback_amount_processing'] = $item['6'];

				date_default_timezone_set('Asia/Ho_Chi_Minh');

				if (intval($cashback_metas['_cashback_amount']) > intval($cashback_metas['_cashback_amount_real'])):
					$cashback_metas['_cashback_status']            = 'processing';
					$cashback_metas['_cashback_amount_processing'] = intval($cashback_metas['_cashback_amount']) - intval($cashback_metas['_cashback_amount_real']);
				else:
					$cashback_metas['_cashback_status']            = 'success';
					$cashback_metas['_cashback_amount_processing'] = 0;
					$cashback_metas['_cashback_date']              = date("d/m/Y H:i");
				endif;

				if ($cashback_metas['_cashback_amount'] == 0 || $cashback_metas['_cashback_amount'] == '0'):
					$cashback_metas['_cashback_status'] = 'success';
				endif;

				if (!empty($cashback_metas)):
					foreach ($cashback_metas as $meta_key => $meta_value):
						update_post_meta($cashback_id, $meta_key, $meta_value);
					endforeach;
				endif;

				array_push($imported_data, $cashback_metas['_cashback_package']);
			else:
				$status = 'complete';
				break;
			endif;
		endfor;
	endif;

	$response = [
		'imported_data' => $imported_data,
		'end_row'       => $end_row,
		'status'        => $status
	];

	wp_send_json_success($response);
	wp_die();
}

add_action('wp_ajax_cashback_importer', '_n_ajax_cashback_importer');
