<?php
/**
 * N Framework
 *
 * WARNING: This file is part of the core N Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @since      0.0.1
 * @package    N
 * @subpackage N/lib/admin/import
 */

if (!defined('ABSPATH')):
	exit; // Exit if accessed directly.
endif;


/**
 * Xoá sản phẩm bằng ajax
 */
function _n_ajax_delete_by_history(){
	$history = isset($_POST['history']) ? esc_attr($_POST['history']) : '';

	$args = [
		'post_type'      => 'package',
		'posts_per_page' => - 1,
		'meta_query'     => [
			[
				'key'     => '_import_history',
				'value'   => $history,
				'compare' => '='
			]
		]
	];

	$loop = new WP_Query($args);
	if ($loop->have_posts()):
		while ($loop->have_posts()) : $loop->the_post();
			_n_delete_post_metas(get_the_ID());
		endwhile;
		wp_reset_postdata();
	endif;

	$deleted = wp_delete_post($history, true);

	if ($deleted):
		wp_send_json_success('Đã xoá');
	else:
		wp_send_json_success('Đã có lỗi');
	endif;

	die();
}

add_action('wp_ajax_delete_by_history', '_n_ajax_delete_by_history');

/**
 * Xoá sản phẩm
 */
function _n_delete_post_metas($id){
	$post_meta_keys = get_post_custom_keys($id);

	if ($post_meta_keys):
		foreach ($post_meta_keys as $meta_key):
			delete_post_meta($id, $meta_key);
		endforeach;
	endif;

	wp_delete_post($id, true);
}
