<?php
/**
 * N Framework
 *
 * WARNING: This file is part of the core N Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @since      0.0.1
 * @package    N
 * @subpackage N/lib/admin
 */

if (!defined('ABSPATH')):
	exit; // Exit if accessed directly.
endif;

use Shuchkin\SimpleXLSX;

/**
 * Sim importer with ajax
 *
 * @since 0.0.1
 */
function _n_ajax_package_importer(){
	if (!(is_array($_POST) && is_array($_FILES) && defined('DOING_AJAX') && DOING_AJAX)):
		wp_send_json_error('Lỗi');
	endif;

	$file                   = $_FILES['file'] ?? null;
	$start_row              = isset($_POST['start_row']) ? intval($_POST['start_row']) : 1;
	$history                = isset($_POST['history']) ? intval($_POST['history']) : 0;
	$package_special_offers = isset($_POST['package_special_offers']) ? strval($_POST['package_special_offers']) : '';
	$mno                    = isset($_POST['mno']) ? strval($_POST['mno']) : '';
	$batch_size             = 100;
	$end_row                = $start_row + $batch_size - 1;
	$imported_data          = [];
	$status                 = 'complete';

	if ($xlsx = SimpleXLSX::parse($file['tmp_name']) && $xlsx_rows = SimpleXLSX::parse($file['tmp_name'])->rows()):
		$count = count($xlsx_rows) - 5;

		if (!function_exists('post_exists')):
			require_once(ABSPATH . 'wp-admin/includes/post.php');
		endif;

		if ($history == 0):
			$args = [
				'post_type'   => 'import_history',
				'post_status' => 'publish',
			];

			$import_history_id = wp_insert_post($args);

			if (!is_wp_error($import_history_id)):
				update_post_meta($import_history_id, '_file_name', $file['name']);
				$history = $import_history_id;
			endif;
		endif;

		if ($start_row <= $count):
			$status = 'continue';
		endif;

		for ($row = $start_row; $row <= $end_row; $row ++):
			if ($row <= 4):
				continue;
			endif;

			if (isset($xlsx_rows[$row])):
				$item                 = $xlsx_rows[$row];
				$package_metas        = [];
				$package_types        = $item['2'];
				$package_preferential = $item['6'];
				$package_type_args    = explode(', ', $package_types);

				if (!empty($package_type_args)):
					foreach ($package_type_args as $package_type):
						if ($package_type == 'Data'):
							$package_metas['_package_is_data'] = 'yes';
						endif;

						if ($package_type == 'Thoại'):
							$package_metas['_package_call'] = 'yes';
						endif;

						if ($package_type == 'SMS'):
							$package_metas['_package_sms'] = 'yes';
						endif;
					endforeach;
				endif;

				if ($package_special_offers != ''):
					$package_metas['_package_special_offers'] = 'yes';
				endif;

				if ($mno != ''):
					$package_metas['_mno'] = $mno;
				endif;

				$package_preferential_args = explode("\n", $package_preferential);
				$package_preferential_args = array_filter($package_preferential_args, 'strlen');

				if (!empty($package_preferential_args)):
					$package_metas['_package_preferential'] = count($package_preferential_args);
					foreach ($package_preferential_args as $key => $package_preferential_arg):
						$package_metas["_package_preferential_{$key}__text"] = $package_preferential_arg;
					endforeach;
				endif;

				$package_metas['_package_name']   = $item['1'];
				$package_metas['_package_price']  = str_replace(['.', ','], '', $item['3']);
				$package_metas['_package_cycle']  = str_replace(['Ngày', ' Ngày'], '', $item['4']);
				$package_metas['_package_refund'] = str_replace(['.', ','], '', $item['7']);
				$package_metas['_package_data']   = $item['5'];

				if ($package_metas['_package_cycle'] < 30):
					$package_metas['_package_day'] = 'yes';
				endif;

				if ($package_metas['_package_cycle'] >= 30 && $package_metas['_package_cycle'] < 360):
					$package_metas['_package_month'] = 'yes';
				endif;

				if ($package_metas['_package_cycle'] >= 360):
					$package_metas['_package_year'] = 'yes';
				endif;

				if ($history > 0):
					$package_metas['_import_history'] = $history;
				endif;

				$package_args = [
					'post_type'   => 'package',
					'post_status' => 'publish',
					'post_title'  => $package_metas['_package_name'],
				];

				$package_id = wp_insert_post($package_args);

				if (!is_wp_error($package_id)):
					if (!empty($package_metas)):
						foreach ($package_metas as $meta_key => $meta_value):
							update_post_meta($package_id, $meta_key, $meta_value);
						endforeach;
					endif;

					array_push($imported_data, $package_metas['_package_name']);
				endif;
			else:
				$status = 'complete';
				break;
			endif;
		endfor;
	endif;

	$response = [
		'imported_data' => $imported_data,
		'end_row'       => $end_row,
		'history'       => $history,
		'status'        => $status
	];

	wp_send_json_success($response);
	wp_die();
}

add_action('wp_ajax_package_importer', '_n_ajax_package_importer');
