<?php
/**
 * N Framework
 *
 * WARNING: This file is part of the core N Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @since 0.0.1
 * @package    N
 * @subpackage N/includes/classes
 */

if (!defined('ABSPATH')):
	exit; // Exit if accessed directly.
endif;

/**
 * N pagination class
 *
 * @since      0.0.1
 */
class NPagination {

	/**
	 * Get an instance of the class.
	 *
	 * @since 0.0.1
	 */
	public static function get(){
		return new NPagination();
	}

	/**
	 * Get the pagination.
	 *
	 * @since 0.0.1
	 */
	public function get_pagination($args = []){
		$this->pagination($args);
	}

	/**
	 * The pagination.
	 *
	 * @since 0.0.1
	 */
	private function pagination($args = []){
		$defaults = [
			'prev' => 'Prev',
			'next' => 'Next',
			'echo' => true
		];

		$args        = wp_parse_args($args, $defaults);
		$args        = (object) $args;
		$query       = $GLOBALS['wp_query'];
		$paged       = max(1, absint($query->get('paged')));
		$total_pages = max(1, absint($query->max_num_pages));

		if ($total_pages == 1):
			return '';
		endif;

		$pages_to_show         = 5;
		$pages_to_show_minus_1 = $pages_to_show - 1;
		$half_page_start       = floor($pages_to_show_minus_1 / 2);
		$half_page_end         = ceil($pages_to_show_minus_1 / 2);
		$start_page            = $paged - $half_page_start;

		if ($start_page <= 0):
			$start_page = 1;
		endif;

		$end_page = $paged + $half_page_end;

		if (($end_page - $start_page) != $pages_to_show_minus_1):
			$end_page = $start_page + $pages_to_show_minus_1;
		endif;

		if ($end_page > $total_pages):
			$start_page = $total_pages - $pages_to_show_minus_1;
			$end_page   = $total_pages;
		endif;

		if ($start_page < 1):
			$start_page = 1;
		endif;

		$out = '<nav class="n-page-nav-wrapper">';

		// Previous
		if ($paged > 1):
			$out .= '<a class="page-nav-prev" href="' . get_pagenum_link($paged - 1) . '">' . $args->prev . '</a>';
		endif;

		$out .= '<ul class="page-nav-main">';

		// First
		if ($start_page >= 2 && $pages_to_show < $total_pages):
			$out .= '<li class="page-nav-item"><a href="' . get_pagenum_link(1) . '">1</a></li>';
		endif;

		// Dots left
		if ($start_page >= 2 && $pages_to_show < $total_pages):
			$out .= '<li class="page-nav-item page-nav-item-skip page-nav-item-skip-start"><a href="javascript:;">...</a></li>';
		endif;

		// Page numbers
		foreach (range($start_page, $end_page) as $i):
			if ($i == $paged):
				$classes = 'page-nav-item page-nav-item-current';
			elseif ($i < $paged):
				$classes = 'page-nav-item page-nav-item-earlier';
			elseif ($i > $paged):
				$classes = 'page-nav-item page-nav-item-later';
			else:
				$classes = 'page-nav-item';
			endif;

			$out .= '<li class="' . $classes . '"><a href="' . get_pagenum_link($i) . '">' . $i . '</a></li>';
		endforeach;

		if ($end_page < $total_pages):
			$out .= '<li class="page-nav-item page-nav-item-skip page-nav-item-skip-end"><a href="javascript:;">...</a></li>';
		endif;

		// Last
		if ($end_page < $total_pages):
			$out .= '<li class="page-nav-item"><a href="' . get_pagenum_link($total_pages) . '">' . $total_pages . '</a></li>';
		endif;

		$out .= '</ul>';

		// Next
		if ($paged < $total_pages):
			$out .= '<a class="page-nav-next" href="' . get_pagenum_link($paged + 1) . '">' . $args->next . '</a>';
		endif;

		$out .= '</nav>';

		if ($args->echo):
			echo $out;

			return '';
		endif;

		return $out;
	}
}
